### ISSUE TITLE
DSA key changing in each run

### ISSUE THREAD

**Issue by Josan-Coba** [flyingarg/bgppp#18]
Each time the program is stopped and executed again the DSA key of the hosts changes, arising ssh warning about a possible eavesdropping attack, failing the host key verification check and cutting down the connection. This is specially annoying when testing because it forces you to make the ssh to forgot the old key and accept the new one everytime you have to re-run the system.
Is there a known (and not-too-hard) way of fixing this and giving each host a fixed key, maybe provided in the config file?

/cc @flyingarg

**Comment by flyingarg** [comment]
The server that we use belongs to the following project. 
http://mina.apache.org/sshd-project/embedding_ssh.html

On the above page, does the section KeyPairProvider relate to the above problem ?

**Comment by Josan-Coba** [comment]
I've been playing with `setKeyPairProvider` and the `SimpleGeneratorHostKeyProvider` class. It seems that it can build the key file if it's in the same folder as the executable and then the issue is fixed between executions, but I'm finding some troubles when trying to put the key in a parent folder (i.e. out of the `target` folder) in order to keep the key also between compilations. The function is simply not creating the file.

**Comment by flyingarg** [comment]
cool, can u make the commit where the file is created 'IN the target' folder. So that we can all have a look at fix try our luck.
