### ISSUE TITLE
When and Where and How of Update Messages.

### ISSUE THREAD

**Issue by flyingarg** [flyingarg/bgppp#19]
Can we prepare an initial draft of how the update messages work, when they are called and how they are processed ? 
The Information can be obtained from <code>http://www.ietf.org/rfc/rfc4271.txt</code> Section 5.
If we have some sort of concise goto document, then we can add it to the report for next week and also add to a wiki here.
I know its a bunch of reading, but we have to present a final report anyways and that can be added to it.

Once that is done. We can sit and code and I can walk you through the most interesting parts where the update messages can be added.

**Comment by Josan-Coba** [comment]
This is not going to be ready for tomorrow's report, but is probably going to be by the end of the weekend.

**Comment by flyingarg** [comment]
That's fine.
